# Generated by Django 5.2 on 2025-04-26 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_code_age_user_created_at_alter_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='赏金')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('open', '开放中'), ('in_progress', '进行中'), ('completed', '已完成'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('bounty_type', models.CharField(choices=[('bug', '漏洞挖掘'), ('development', '功能开发'), ('design', '设计任务'), ('other', '其他类型')], max_length=20, verbose_name='类型')),
                ('tech_stack', models.CharField(blank=True, max_length=200, verbose_name='技术栈')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='难度等级')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('favorites', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bounties', to='user.user', verbose_name='创建者')),
                ('solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_bounties', to='user.user', verbose_name='解决者')),
            ],
            options={
                'verbose_name': '悬赏任务',
                'verbose_name_plural': '悬赏任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
