# Generated by Django 5.2.1 on 2025-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_app', '0003_alter_reward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('completed', 'Completed'), ('payed', 'Payed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
